# history
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY 

setopt extendedglob notify
bindkey -e

#
# auto completion
#
autoload -Uz compinit
compinit
setopt autocd
# correct mistakes:
setopt CORRECT
setopt AUTO_LIST
# allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD
# tab completion moves to end of word
setopt ALWAYS_TO_END
setopt listtypes
# a leading space prevents the command from being saved to the history
setopt HIST_IGNORE_SPACE

unalias run-help
autoload run-help

# allow approximate completion
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
                             /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

# history search
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

# colorful PS1
autoload colors; colors
export PS1="%B[%{$fg[green]%}%n%{$reset_color%}%b@%B%{$fg[red]%}%M%b%{$reset_color%}:%{$fg[yellow]%}%~%{$reset_color%}%B]%b "

# ctrl-left/right
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

# ctrl-backspace/delete
bindkey "\C-_" backward-kill-word
bindkey "\e[3;5~" kill-word

# alt-backspace
bindkey "\e\d" undo

bindkey "\e[3~" delete-char
bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line

#
# direcotry history
#

DIRSTACKFILE="$HOME/.zsh_dirstack"
if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
  dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
  [[ -d $dirstack[1] ]] && cd $dirstack[1]
fi
chpwd() {
  print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
}

DIRSTACKSIZE=100

setopt autopushd pushdsilent pushdtohome

# Remove duplicate entries
setopt pushdignoredups

# This reverts the +/- operators.
setopt pushdminus

#
# Alt-Up, Alt-Left directory navigation
#

cdUndoKey() {
  popd      > /dev/null
  zle       reset-prompt
  echo
  ls
  echo
}

cdParentKey() {
  pushd .. > /dev/null
  zle      reset-prompt
  echo
  ls
  echo
}

zle -N                 cdParentKey
zle -N                 cdUndoKey
bindkey '^[[1;3A'      cdParentKey
bindkey '^[[1;3D'      cdUndoKey

#
# aliases
#

alias cp='cp --reflink=auto --sparse=always'
alias ls='ls --color=auto -F --time-style=+"%Y-%m-%d %H:%M:%S"'
alias l="ls -hl"
alias ll="l -a"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias today="date +%y%m%d"
alias today2="date +%Y%m%d"
alias now="date +%y%m%d%H%M%S"
alias now2="date +%Y%m%d%H%M%S"
alias nprocplus1="echo $(($(nproc)+1))"
alias nano="nano -cAiw"
