#!/bin/bash

tmp_file=/tmp/mp3fs_mounts

function all_mount_points {
    cat $tmp_file | xargs -L1 -P0 $@
}

case $1 in
    hibernate)
    	# s2disk
    ;;
    suspend)
    	# s2ram
    	mount | grep mp3fs | awk '{print $3}' > $tmp_file
    	all_mount_points umount
    ;;
    thaw)
    	# resume from s2disk
    ;;
    resume)
    	# resume from s2ram
    	all_mount_points mount
    	rm $tmp_file
    ;;
    *)
    	# unknown argument
    ;;
esac
